export const voices = 
[
    {"name":"Rachel"   , "voice_id":"21m00Tcm4TlvDq8ikWAM", "labels":" american, calm, young,  female, narration"},
    {"name":"Clyde"    , "voice_id":"2EiwWnXFnvU5JabPnv8n", "labels":"american, war veteran, middle aged,  male,  video games"}, 
    {"name":"Domi"     , "voice_id":"AZnzlk1XvdvUeBnXmlld", "labels":"american, strong, young,  female,  narration"},
    {"name":"Dave"     , "voice_id":"CYw3kZ02Hs0563khs1Fj", "labels":"british-essex, conversational, young,  male,  video games"},
    {"name":"Fin"      , "voice_id":"D38z5RcWu1voky8WS1ja", "labels":"irish, sailor, old,  male,  video games"},
    {"name":"Bella"    , "voice_id":"EXAVITQu4vr4xnSDxMaL", "labels":"american, soft, young,  female,  narration"},
    {"name":"Antoni"   , "voice_id":"ErXwobaYiN019PkySvjV", "labels":"american, well-rounded, young,  male,  narration"},
    {"name":"Thomas"   , "voice_id":"GBv7mTt0atIp3Br8iCZE", "labels":"american, calm, young,  male,  meditation"},
    {"name":"Charlie"  , "voice_id":"IKne3meq5aSn9XLyUdCD", "labels":"australian, casual, middle aged,  male,  conversational"},
    {"name":"Emily"    , "voice_id":"LcfcDJNUP1GQjkzn1xUU", "labels":"american, calm, young,  female,  meditation"},
    {"name":"Elli"     , "voice_id":"MF3mGyEYCl7XYWbV9V6O", "labels":"american, emotional, young,  female,  narration"},
    {"name":"Callum"   , "voice_id":"N2lVS1w4EtoT3dr4eOWO", "labels":"american, hoarse, middle aged,  male,  video games"},
    {"name":"Patrick"  , "voice_id":"ODq5zmih8GrVes37Dizd", "labels":"american, shouty, middle aged,  male,  video games"},
    {"name":"Harry"    , "voice_id":"SOYHLrjzK2X1ezoPC6cr", "labels":"american, anxious, young,  male,  video games"},
    {"name":"Liam"     , "voice_id":"TX3LPaxmHKxFdv7VOQHJ", "labels":"american, young,  male,  narration, neutral"},
    {"name":"Dorothy"  , "voice_id":"ThT5KcBeYPX3keUQqHPh", "labels":"british, pleasant, young,  female,  children's stories"},
    {"name":"Josh"     , "voice_id":"TxGEqnHWrfWFTfGW9XjX", "labels":"american, deep, young,  male,  narration"},
    {"name":"Arnold"   , "voice_id":"VR6AewLTigWG4xSOukaG", "labels":"american, crisp, middle aged,  male,  narration"},
    {"name":"Charlotte", "voice_id":"XB0fDUnXU5powFXDhCwa", "labels":"english-swedish, seductive, middle aged,  female,  video games"},
    {"name":"Matilda"  , "voice_id":"XrExE9yKIg1WjnnlVkGX", "labels":"american, warm, young,  female,  audiobook"},
    {"name":"Matthew"  , "voice_id":"Yko7PKHZNXotIFUBG7I9", "labels":"british, middle aged,  male,  audiobook, calm"},
    {"name":"James"    , "voice_id":"ZQe5CZNOzWyzPSCn5a3c", "labels":"australian, calm , old,  male,  news"},
    {"name":"Joseph"   , "voice_id":"Zlb1dXrM653N07WRdFW3", "labels":"british, middle aged,  male,  news, ground reporter "},
    {"name":"Jeremy"   , "voice_id":"bVMeCyTHy58xNoL34h3p", "labels":"american-irish, excited, young,  male,  narration"},
    {"name":"Michael"  , "voice_id":"flq6f7yk4E4fJM5XTYuZ", "labels":"american, old,  male,  audiobook, orotund"},
    {"name":"Ethan"    , "voice_id":"g5CIjZEefAph4nQFvHAz", "labels":"american, young,  male,  ASMR, whisper"},
    {"name":"Gigi"     , "voice_id":"jBpfuIE2acCO8z3wKNLl", "labels":"american, childlish, young,  female,  animation"},
    {"name":"Freya"    , "voice_id":"jsCqWAovK2LkecY7zXl4", "labels":"american, young,  female, overhyped, video games"},
    {"name":"Grace"    , "voice_id":"oWAxZDx7w5VEj9dCyTzz", "labels":"american-southern, young,  female,  audiobook , gentle"},
    {"name":"Daniel"   , "voice_id":"onwK4e9ZLuTAKqWW03F9", "labels":"british, deep, middle aged,  male,  news presenter"},
    {"name":"Serena"   , "voice_id":"pMsXgVXv3BLzUgSXRplE", "labels":"american, pleasant, middle aged,  female,  interactive"},
    {"name":"Adam"     , "voice_id":"pNInz6obpgDQGcFmaJgB", "labels":"american, deep, middle aged,  male,  narration"},
    {"name":"Nicole"   , "voice_id":"piTKgcLEGmPE4e6mEKli", "labels":"american, whisper, young,  female,  audiobook"},
    {"name":"Jessie"   , "voice_id":"t0jbNlBVZ17f02VDIeMI", "labels":"american, raspy , old,  male,  video games"},
    {"name":"Ryan"     , "voice_id":"wViXBPUzp2ZZixB1xQuM", "labels":"middle aged, soldier,american,  male,  audiobook"},
    {"name":"Sam"      , "voice_id":"yoZ06aMxZJJ28mfd3POQ", "labels":"american, raspy, young,  male,  narration"},
    {"name":"Glinda"   , "voice_id":"z9fAnlkpzviPz146aGWa", "labels":"american, witch, middle aged,  female,  video games"},
    {"name":"Giovanni" , "voice_id":"zcAOhNBS3c14rBihAFp1", "labels":"english-italian, foreigner, young,  male,  audiobook"},
    {"name":"Mimi"     , "voice_id":"zrHiDhphv9ZnVXBqCLjz", "labels":"english-swedish, childish, young,  female,  animation"}
]
